influx_enabled: false
debug_bm1366: false

piaxe:
  sdn_pin: 11
  pgood_pin: 13
  nrst_pin: 15
  led_pin: 19
  pwm_hz: 1000
  pwm_duty_cycle: 80
  lm75_address: 0x48
  serial_port: "/dev/ttyS0"

alerter:
  type: discord-webhook
  enabled: false
  # file: load from file
  url: file://webhook.url
  name: Piaxe1
  retrigger_time: 3600