debug_bm1366: true
verify_solo: true
miner: qaxe

piaxe:
  name: PiAxe
  asic_frequency: 485
  sdn_pin: 11
  pgood_pin: 13
  nrst_pin: 15
  led_pin: 19
  pwm_hz: 1000
  pwm_duty_cycle: 80
  lm75_address: 0x48
  serial_port: "/dev/ttyS0"

bitcrane:
  name: BitCrane
  asic_frequency: 300
  fan_speed: 0.25

qaxe:
  name: Qaxe
  asic_frequency: 485
  serial_port_asic: "/dev/ttyACM1"
  serial_port_ctrl: "/dev/ttyACM2"

alerter:
  enabled: false
  type: discord-webhook
  # file: load from file
  url: file://webhook.url
  name: Piaxe1
  retrigger_time: 3600


influx:
  enabled: false
  host: localhost
  port: 8086
  token: f37fh783hf8hq
  org: piaxe
  bucket: piaxe
  timezone: Europe/Berlin
